-- MySQL Script generated by MySQL Workbench
-- Tue Sep 14 11:14:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`constructora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`constructora` (
  `con_id` INT NOT NULL,
  `con_estado` TINYINT NOT NULL DEFAULT 1,
  `con_nombre_empresa` VARCHAR(10) NULL,
  `con_id_identificacion` INT NULL,
  `con_sigla_identificacion` INT NULL,
  `con_created_at` TIMESTAMP NULL,
  `con_updated_at` TIMESTAMP NULL,
  `con_usuSesion` VARCHAR(20) NULL,
  `usuario_s_usuld` INT NULL,
  PRIMARY KEY (`con_id`),
  INDEX `fk_constructora_identificacion1_idx` (`con_id_identificacion` ASC, `con_sigla_identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_constructora_identificacion1`
    FOREIGN KEY (`con_id_identificacion` , `con_sigla_identificacion`)
    REFERENCES `mydb`.`identificacion` (`ide_id` , `ide_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`identificacion` (
  `ide_id` INT NOT NULL,
  `ide_sigla` INT NULL,
  `ide_estado` TINYINT NOT NULL DEFAULT 1,
  `ide_created_at` TIMESTAMP NULL,
  `ide_updated_at` TIMESTAMP NULL,
  `ide_usuSesion` VARCHAR(20) NULL,
  PRIMARY KEY (`ide_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`material_construccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material_construccion` (
  `mat_id` INT NOT NULL,
  `mat_nombre_material` VARCHAR(45) NULL,
  `mat_tipo_material` VARCHAR(45) NULL,
  `mat_precio` INT NULL,
  `mat_estado` TINYINT NULL DEFAULT 1,
  `mat_created_at` TIMESTAMP NULL,
  `mat_updated_at` TIMESTAMP NULL,
  `mat_usuSesion` VARCHAR(20) NULL,
  PRIMARY KEY (`mat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `pro_id` INT NOT NULL,
  `material_construccion_mat_id` INT NULL,
  `pro_tipo_proyecto` VARCHAR(50) NULL,
  `pro_nombre_proyecto` VARCHAR(50) NULL,
  `pro_numero_proyecto` INT NULL,
  `pro_descripcion_proyecto` VARCHAR(100) NULL,
  `pro_fecha_inicio` DATE NULL,
  `pro_fecha_fin` DATE NULL,
  `pro_estado` TINYINT NOT NULL DEFAULT 1,
  `pro_sede_id` INT NULL,
  `pro_recibido_id` INT NULL,
  `pro_trabajador_id` INT NULL,
  `pro_created_at` TIMESTAMP NULL,
  `pro_updated_at` TIMESTAMP NULL,
  `pro_usuSesion` VARCHAR(20) NULL,
  PRIMARY KEY (`pro_id`),
  INDEX `fk_proyecto_material_construccion_idx` (`material_construccion_mat_id` ASC) VISIBLE,
  INDEX `fk_proyecto_sede1_idx` (`pro_sede_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_material_construccion`
    FOREIGN KEY (`material_construccion_mat_id`)
    REFERENCES `mydb`.`material_construccion` (`mat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_sede1`
    FOREIGN KEY (`pro_sede_id`)
    REFERENCES `mydb`.`sede` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `rol_id_rol` INT NOT NULL DEFAULT 1,
  `rol_tipo_rol` VARCHAR(10) NOT NULL,
  `rol_estado` TINYINT NOT NULL DEFAULT 1,
  `rol_created_at` TIMESTAMP(10) NULL,
  `rol_updated_at` TIMESTAMP(10) NULL,
  `rol_usuSesion` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_id_rol`),
  UNIQUE INDEX `tipoRol_UNIQUE` (`rol_tipo_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sede` (
  `sede_id` INT NULL,
  `sede_fecha_modificacion` VARCHAR(45) NULL,
  `sede_estado` TINYINT NOT NULL DEFAULT 1,
  `sede_ubicacion_id` INT NULL,
  `sede_nombre_sede` VARCHAR(45) NULL,
  `sede_constructora_id` INT NULL,
  `sede_created_at` TIMESTAMP NULL,
  `sede_updated_at` TIMESTAMP NULL,
  `sede_usuSesion` VARCHAR(20) NULL,
  PRIMARY KEY (`sede_id`),
  UNIQUE INDEX `sede_ide_UNIQUE` (`sede_id` ASC) VISIBLE,
  INDEX `fk_sede_constructora1_idx` (`sede_constructora_id` ASC) VISIBLE,
  INDEX `fk_sede_ubicacion1_idx` (`sede_ubicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_sede_constructora1`
    FOREIGN KEY (`sede_constructora_id`)
    REFERENCES `mydb`.`constructora` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sede_ubicacion1`
    FOREIGN KEY (`sede_ubicacion_id`)
    REFERENCES `mydb`.`ubicacion` (`ubi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ubicacion` (
  `ubi_id` INT NOT NULL,
  `ubi_estado` TINYINT NOT NULL DEFAULT 1,
  `ubi_direccion` VARCHAR(50) NULL,
  `ubi_created_at` TIMESTAMP NULL,
  `ubi_updated_at` TIMESTAMP NULL,
  `ubi_usuSesion` VARCHAR(20) NULL,
  `ubicacioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`ubi_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
